### ISSUE TITLE
Add Git id / version id in standard output

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#199]
For long term usage we need to print the exact version source code that was used to perform a run.
I know it is possible to have git add an id in a specific file which can then be part of the start output of a nest-mc run

**Comment by halfflat** [comment]
Agreed. We haven't got any well-defined output formats (or schemata for output formats) yet — it's all a bit ad hoc.

As part of this issue, we should determine how to consistently represent software version, build environment and invocation in our output formats from any front-end we write (i.e. for now, the miniapp), and how to make it available programmatically, regarding NestMC as a library.

'It would be nice' if we could also include hashes or other identifying metadata for any input files.

**Comment by halfflat** [comment]
This is now provided on the library side (but not in the example code) by the configure-time generated `arbor/version.hpp` header, which gets installed, and by the compile-time `const char[]` arrays `arb::version` and `arb::source_id`.

These are available as preprocessor symbols and as library data so that one can also check at run-time for header/library version mismatch.

The contents of these symbols and strings is not yet documented (it's a TODO), but there is a test in `test/unit/test_version.cpp` that gives an idea.

Addressed in PR #506.
